/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ain jelita ikhwati
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class dashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form dashboardAdmin
     */
    public dashboardAdmin() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        javax.swing.JSpinner.NumberEditor editor = new javax.swing.JSpinner.NumberEditor(spTahun, "####");
        spTahun.setEditor(editor);
        loadStatistic();
        loadChart();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnlogout1 = new javax.swing.JButton();
        lebeluser = new javax.swing.JLabel();
        labelrol = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelAngkaTerjual = new javax.swing.JLabel();
        lblProdukTerjual = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalMenu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelAngkaPendapatan = new javax.swing.JLabel();
        lblPendapatan = new javax.swing.JLabel();
        panelGrafik = new javax.swing.JPanel();
        cbBulan = new javax.swing.JComboBox<>();
        spTahun = new javax.swing.JSpinner();
        btnproduk = new javax.swing.JButton();
        btnlogout2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 210, 182));

        jPanel3.setBackground(new java.awt.Color(117, 117, 74));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");

        btnlogout1.setBackground(new java.awt.Color(225, 0, 0));
        btnlogout1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout1.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout1.setText("LOGOUT");
        btnlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(218, 218, 218)
                .addComponent(btnlogout1)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnlogout1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lebeluser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lebeluser.setText("Username: anjeli");
        lebeluser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lebeluserInputMethodTextChanged(evt);
            }
        });

        labelrol.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        labelrol.setText("Role: Admin");

        jPanel4.setBackground(new java.awt.Color(117, 117, 74));

        labelAngkaTerjual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        labelAngkaTerjual.setForeground(new java.awt.Color(255, 255, 255));
        labelAngkaTerjual.setText("PRODUK TERJUAL");

        lblProdukTerjual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblProdukTerjual.setForeground(new java.awt.Color(255, 255, 255));
        lblProdukTerjual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProdukTerjual.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(labelAngkaTerjual)
                .addGap(68, 68, 68))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProdukTerjual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAngkaTerjual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdukTerjual)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(117, 117, 74));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU TERLARIS");

        lblTotalMenu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblTotalMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalMenu.setText("0");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTotalMenu)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalMenu)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(117, 117, 74));

        labelAngkaPendapatan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        labelAngkaPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        labelAngkaPendapatan.setText("PENDAPATAN");

        lblPendapatan.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lblPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        lblPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendapatan.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(labelAngkaPendapatan)
                .addGap(72, 72, 72))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPendapatan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAngkaPendapatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPendapatan)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGrafikLayout = new javax.swing.GroupLayout(panelGrafik);
        panelGrafik.setLayout(panelGrafikLayout);
        panelGrafikLayout.setHorizontalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGrafikLayout.setVerticalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Juli", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });

        loadStatistic();
        loadChart();
        spTahun.setModel(new javax.swing.SpinnerNumberModel(2026, 2020, 2100, 1));

        btnproduk.setBackground(new java.awt.Color(117, 117, 74));
        btnproduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnproduk.setForeground(new java.awt.Color(242, 242, 242));
        btnproduk.setText("DATA PRODUK");
        btnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodukActionPerformed(evt);
            }
        });

        btnlogout2.setBackground(new java.awt.Color(117, 117, 74));
        btnlogout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout2.setForeground(new java.awt.Color(242, 242, 242));
        btnlogout2.setText("DATA USER");
        btnlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(117, 117, 74));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("KINERJA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelrol)
                                .addComponent(lebeluser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelGrafik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(283, 283, 283)))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lebeluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelrol)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogout2)
                    .addComponent(btnproduk)
                    .addComponent(spTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Anda yakin ingin logout?",
            "Konfirmasi Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {

            // 2. Sembunyikan frame Menu saat ini
            this.setVisible(false);

            // 3. Tampilkan kembali frame Login
            // Catatan: Asumsikan kelas login Anda bernama 'Login'.
            // Anda mungkin perlu menyesuaikannya jika nama kelasnya berbeda.
            try {
                // Membuat instance baru dari kelas Login dan menampilkannya
                login loginFrame = new login();
                loginFrame.setVisible(true);
            } catch (Exception e) {
                // Handle jika kelas Login tidak ditemukan atau error inisialisasi
                JOptionPane.showMessageDialog(this, "Gagal memuat halaman Login. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnlogout1ActionPerformed
private void loadStatistic() {
    // 1. Ambil input dari filter UI
    int bulan = cbBulan.getSelectedIndex() + 1;
    int tahun = (int) spTahun.getValue();

    try {
        java.sql.Connection conn = Config.configDB();

        // --- 1. LOGIKA PRODUK TERLARIS (Periode) ---
        // Kita JOIN kasir2 dengan kasir untuk dapet tanggalnya
        String sqlLaris = "SELECT k2.nama_barang, SUM(k2.jumlah) AS qty " +
                          "FROM kasir2 k2 " +
                          "JOIN kasir k ON k2.no_factur = k.no_factur " +
                          "WHERE MONTH(STR_TO_DATE(k.tanggal, '%d-%m-%Y')) = ? " +
                          "AND YEAR(STR_TO_DATE(k.tanggal, '%d-%m-%Y')) = ? " +
                          "GROUP BY k2.nama_barang ORDER BY qty DESC LIMIT 1";
        
        java.sql.PreparedStatement psLaris = conn.prepareStatement(sqlLaris);
        psLaris.setInt(1, bulan);
        psLaris.setInt(2, tahun);
        java.sql.ResultSet rsLaris = psLaris.executeQuery();
        
        if (rsLaris.next()) {
            lblTotalMenu.setText(rsLaris.getString("nama_barang") + " (" + rsLaris.getInt("qty") + ")");
        } else {
            lblTotalMenu.setText("-");
        }

        // --- 2. LOGIKA PRODUK TERJUAL (Periode) ---
        String sqlTerjual = "SELECT SUM(k2.jumlah) " +
                            "FROM kasir2 k2 " +
                            "JOIN kasir k ON k2.no_factur = k.no_factur " +
                            "WHERE MONTH(STR_TO_DATE(k.tanggal, '%d-%m-%Y')) = ? " +
                            "AND YEAR(STR_TO_DATE(k.tanggal, '%d-%m-%Y')) = ?";
        
        java.sql.PreparedStatement psTerjual = conn.prepareStatement(sqlTerjual);
        psTerjual.setInt(1, bulan);
        psTerjual.setInt(2, tahun);
        java.sql.ResultSet rsTerjual = psTerjual.executeQuery();
        
        if (rsTerjual.next()) {
            String qty = rsTerjual.getString(1);
            lblProdukTerjual.setText(qty == null ? "0" : qty);
        }

        // --- 3. LOGIKA PENDAPATAN (Periode) ---
        String sqlPendapatan = "SELECT SUM(total) FROM kasir " +
                               "WHERE MONTH(STR_TO_DATE(tanggal, '%d-%m-%Y')) = ? " +
                               "AND YEAR(STR_TO_DATE(tanggal, '%d-%m-%Y')) = ?";
        
        java.sql.PreparedStatement psPendapatan = conn.prepareStatement(sqlPendapatan);
        psPendapatan.setInt(1, bulan);
        psPendapatan.setInt(2, tahun);
        java.sql.ResultSet rsPendapatan = psPendapatan.executeQuery();
        
        if (rsPendapatan.next()) {
            double angka = rsPendapatan.getDouble(1);
            lblPendapatan.setText("Rp " + String.format("%,.0f", angka));
        }

    } catch (Exception e) {
        System.out.println("Error Statistik Periode: " + e.getMessage());
    }
}
    
    
    private void loadChart() {
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();

        // Ambil input dari JComboBox bulan dan JSpinner tahun
        int bulan = cbBulan.getSelectedIndex() + 1; 
        int tahun = (int) spTahun.getValue();

        try {
            java.sql.Connection conn = Config.configDB();

            // Query disesuaikan dengan tabel 'kasir' dan kolom 'tanggal'
            // Format tanggal di DB kamu (23-12-2025) perlu diconvert atau pastikan formatnya YYYY-MM-DD
            String sql = "SELECT DAY(STR_TO_DATE(tanggal, '%d-%m-%Y')) as tgl, SUM(total) as total " +
                         "FROM `kasir` " +
                         "WHERE MONTH(STR_TO_DATE(tanggal, '%d-%m-%Y')) = ? " +
                         "AND YEAR(STR_TO_DATE(tanggal, '%d-%m-%Y')) = ? " +
                         "GROUP BY tgl";

            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, bulan);
            ps.setInt(2, tahun);
            java.sql.ResultSet rs = ps.executeQuery();

            // Mapping data
            java.util.Map<Integer, Double> dataMap = new java.util.HashMap<>();
            while (rs.next()) {
                dataMap.put(rs.getInt("tgl"), rs.getDouble("total"));
            }

            // Tampilkan 1 - 31 agar grafik rapi
            for (int i = 1; i <= 31; i++) {
                double nilai = dataMap.getOrDefault(i, 0.0);
                dataset.addValue(nilai, "Penjualan", String.valueOf(i));
            }

            // Pembuatan Chart
            org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createBarChart(
                    "Grafik Penjualan Bulanan", "Tanggal", "Total (Rp)", dataset, 
                    org.jfree.chart.plot.PlotOrientation.VERTICAL, false, true, false);

            org.jfree.chart.plot.CategoryPlot plot = chart.getCategoryPlot();
            org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) plot.getRenderer();
            renderer.setSeriesPaint(0, new java.awt.Color(225, 0, 0)); // Merah
            renderer.setMaximumBarWidth(0.1); 

            // Tempel ke panel
            org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
            panelGrafik.removeAll();
            panelGrafik.setLayout(new java.awt.BorderLayout());
            panelGrafik.add(chartPanel, java.awt.BorderLayout.CENTER);
            panelGrafik.validate();
            panelGrafik.repaint();

        } catch (Exception e) {
            System.out.println("Error Grafik Baru: " + e.getMessage());
        }
    }
    
    private void lebeluserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lebeluserInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lebeluserInputMethodTextChanged

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        loadStatistic(); //upadet angka
        loadChart(); //panggil ulang grafik
    }//GEN-LAST:event_cbBulanActionPerformed

    private void btnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodukActionPerformed

    }//GEN-LAST:event_btnprodukActionPerformed

    private void btnlogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout2ActionPerformed
        this.setVisible(false);
        new Menu2().setVisible(true);
    }//GEN-LAST:event_btnlogout2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new kinerjaKasir().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton btnlogout2;
    private javax.swing.JButton btnproduk;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelAngkaPendapatan;
    private javax.swing.JLabel labelAngkaTerjual;
    private javax.swing.JLabel labelrol;
    private javax.swing.JLabel lblPendapatan;
    private javax.swing.JLabel lblProdukTerjual;
    private javax.swing.JLabel lblTotalMenu;
    private javax.swing.JLabel lebeluser;
    private javax.swing.JPanel panelGrafik;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JSpinner spTahun;
    // End of variables declaration//GEN-END:variables
}
