/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import javax.swing.JTable;
/**
 *
 * @author HP
 */
public class Riwayat_keuangan extends javax.swing.JFrame {

    /**
     * Creates new form LaporanKeuangan
     */
    public Riwayat_keuangan() {
        initComponents();
        this.setResizable(false);
        load_table(); // pnggil fungsi load data di sini
    }
    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No Faktur");
    model.addColumn("Tanggal");
    model.addColumn("ID Customer");
    model.addColumn("Total");

    try {
        Connection c = Config.configDB(); 
        Statement s = c.createStatement();
        String sql = "SELECT * FROM kasir"; //mngambil data dari tabel header kasir
        ResultSet r = s.executeQuery(sql);

        while (r.next()) {
            model.addRow(new Object[]{
                r.getString("no_factur"),
                r.getString("tanggal"),
                r.getString("id_customer"),
                r.getString("total")
            });
        }
        tabelbarang.setModel(model);
        hitungTotal(); // Hitung total setiap kali tabel di-load
    } catch (Exception e) {
        System.out.println("Error Load Table: " + e.getMessage());
    }
}

private void hitungTotal() {
    int totalPemasukan = 0;
    for (int i = 0; i < tabelbarang.getRowCount(); i++) {
        // Mengambil nilai dari kolom 'Total' (indeks 3)
        int nilai = Integer.parseInt(tabelbarang.getValueAt(i, 3).toString());
        totalPemasukan += nilai;
    }
    txt_hasilpemasukan.setText("Rp. " + String.valueOf(totalPemasukan));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        btncetaklaporan = new javax.swing.JButton();
        btnhapuslaporan = new javax.swing.JButton();
        txt_hasilpemasukan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnRiwayatPenjualan = new javax.swing.JButton();
        btnRiwayatTransaksi = new javax.swing.JButton();
        btnRiwayatKeuangan = new javax.swing.JButton();
        lebeluser = new javax.swing.JLabel();
        labelrol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 210, 182));

        jPanel2.setBackground(new java.awt.Color(117, 117, 74));

        btnlogout.setBackground(new java.awt.Color(225, 0, 0));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(242, 242, 242));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(117, 117, 74));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("                   RIWAYAT KEUANGAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(btnlogout))
        );

        jPanel3.setBackground(new java.awt.Color(210, 210, 182));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelbarang);

        btncetaklaporan.setBackground(new java.awt.Color(117, 117, 74));
        btncetaklaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncetaklaporan.setForeground(new java.awt.Color(242, 242, 242));
        btncetaklaporan.setText("Cetak Laporan");
        btncetaklaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetaklaporanActionPerformed(evt);
            }
        });

        btnhapuslaporan.setBackground(new java.awt.Color(225, 0, 0));
        btnhapuslaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhapuslaporan.setForeground(new java.awt.Color(242, 242, 242));
        btnhapuslaporan.setText("Hapus");
        btnhapuslaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapuslaporanActionPerformed(evt);
            }
        });

        txt_hasilpemasukan.setEditable(false);
        txt_hasilpemasukan.setBackground(new java.awt.Color(153, 255, 51));
        txt_hasilpemasukan.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        txt_hasilpemasukan.setText("Rp. 0");
        txt_hasilpemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hasilpemasukanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("HASIL PENJUALAN");

        btnRiwayatPenjualan.setBackground(new java.awt.Color(117, 117, 74));
        btnRiwayatPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRiwayatPenjualan.setForeground(new java.awt.Color(242, 242, 242));
        btnRiwayatPenjualan.setText("RIWAYAT PENJUALAN");
        btnRiwayatPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatPenjualanActionPerformed(evt);
            }
        });

        btnRiwayatTransaksi.setBackground(new java.awt.Color(117, 117, 74));
        btnRiwayatTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRiwayatTransaksi.setForeground(new java.awt.Color(242, 242, 242));
        btnRiwayatTransaksi.setText("RIWAYAT TRANSAKSI");
        btnRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatTransaksiActionPerformed(evt);
            }
        });

        btnRiwayatKeuangan.setBackground(new java.awt.Color(117, 117, 74));
        btnRiwayatKeuangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRiwayatKeuangan.setForeground(new java.awt.Color(242, 242, 242));
        btnRiwayatKeuangan.setText("RIWAYAT KEUANGAN");
        btnRiwayatKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatKeuanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_hasilpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhapuslaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncetaklaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnRiwayatTransaksi)
                                .addGap(18, 18, 18)
                                .addComponent(btnRiwayatPenjualan)
                                .addGap(18, 18, 18)
                                .addComponent(btnRiwayatKeuangan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRiwayatTransaksi)
                    .addComponent(btnRiwayatKeuangan)
                    .addComponent(btnRiwayatPenjualan))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btncetaklaporan)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapuslaporan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hasilpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        lebeluser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        lebeluser.setText("Username: Salsa");
        lebeluser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lebeluserInputMethodTextChanged(evt);
            }
        });

        labelrol.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        labelrol.setText("Role: Owner");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lebeluser)
                    .addComponent(labelrol))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lebeluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelrol)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lebeluserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lebeluserInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lebeluserInputMethodTextChanged

    private void btnhapuslaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapuslaporanActionPerformed
        int baris = tabelbarang.getSelectedRow();
    if (baris != -1) {
        String id = tabelbarang.getValueAt(baris, 0).toString();
        int jawab = JOptionPane.showConfirmDialog(null, "Hapus data " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            try {
                Connection c = Config.configDB();
                Statement s = c.createStatement();
                s.executeUpdate("DELETE FROM kasir WHERE no_factur='" + id + "'");
                s.close();
                load_table(); // Refresh tabel
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus terlebih dahulu!");
    }

    }//GEN-LAST:event_btnhapuslaporanActionPerformed

    private void btncetaklaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetaklaporanActionPerformed
    MessageFormat header = new MessageFormat("Laporan Keuangan Coffee Shop");
    MessageFormat footer = new MessageFormat("Halaman {0,number,integer}");
    try {
        tabelbarang.print(JTable.PrintMode.FIT_WIDTH, header, footer);
    } catch (java.awt.print.PrinterException e) {
        System.err.format("Gagal mencetak: %s%n", e.getMessage());
    }

    }//GEN-LAST:event_btncetaklaporanActionPerformed

    private void txt_hasilpemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hasilpemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hasilpemasukanActionPerformed

    private void btnRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatTransaksiActionPerformed
        this.dispose();
        new Riwayat_transaksi().setVisible(true);
        Riwayat_transaksi pindah = new Riwayat_transaksi();
    }//GEN-LAST:event_btnRiwayatTransaksiActionPerformed

    private void btnRiwayatPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatPenjualanActionPerformed
        this.dispose();
        new Riwayat_penjualan().setVisible(true);
    }//GEN-LAST:event_btnRiwayatPenjualanActionPerformed

    private void btnRiwayatKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatKeuanganActionPerformed
        this.dispose();
        new Riwayat_keuangan().setVisible(true);
    }//GEN-LAST:event_btnRiwayatKeuanganActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Anda yakin ingin logout?",
                "Konfirmasi Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            
            // 2. Sembunyikan frame Menu saat ini
            this.setVisible(false);
            
            // 3. Tampilkan kembali frame Login
            // Catatan: Asumsikan kelas login Anda bernama 'Login'.
            try {
                // Membuat instance baru dari kelas Login dan menampilkannya
                login loginFrame = new login();
                loginFrame.setVisible(true);
            } catch (Exception e) {
                // Handle jika kelas Login tidak ditemukan atau error inisialisasi
                JOptionPane.showMessageDialog(this, "Gagal memuat halaman Login. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRiwayatKeuangan;
    private javax.swing.JButton btnRiwayatPenjualan;
    private javax.swing.JButton btnRiwayatTransaksi;
    private javax.swing.JButton btncetaklaporan;
    private javax.swing.JButton btnhapuslaporan;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelrol;
    private javax.swing.JLabel lebeluser;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txt_hasilpemasukan;
    // End of variables declaration//GEN-END:variables
}
